### ISSUE TITLE
Frostbite does not DR

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#11]
**Current behaviour:**
Frostbite proc does not DR with itself

**Expected behaviour:**
Frostbite proc should DR with itself. And I _**think**_ it should be in same DR category as other random root procs such as improved hamstring/wingclip 

**Proof for expected behavior:**
https://youtu.be/J6d3vGyIOw0?t=1019

https://wowwiki-archive.fandom.com/wiki/Diminishing_returns?oldid=1663771
(not the greatest proof but for now its all I found)

**Comment by Aggrend** [comment]
This is fixed in builds after 38195 on beta.
