### ISSUE TITLE
Stoneclaw totem breaking stealth

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#16]
**Current behaviour:**
Currently Stoneclaw Totem does not break stealth. It doesnt not break stealth in Classic either. However there is a WoTLK patchnote metioning 

"Patch 3.2.2 (2009-09-22): "Stoneclaw Totem's pulses will no longer break stealth on nearby hostile units.". 

Which in past puzzled alot of people, and it was never found whether Stoneclaw breaking stealth was all the way up to wotlk, or if it was just some bug made in wotlk and later in 3.2.2 fixed.

**Comment by Aggrend** [comment]
Not a bug. I believe that was simply a bug fix at the time in WotLK and doesn't have relevance for TBC Classic.

**Comment by Aeded** [comment]
Thanks alot for checking on this!

**Comment by Aeded** [comment]
Thanks alot for checking on this!
