### ISSUE TITLE
Windfury Totem and Flametongue Totem trigger combat when used.

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#2]
**Current behaviour:**
When other party members are in combat, dropping down WF totem gives combat to yourself. However totem pulses do not give combat. Application of the weapon buff to party members is possibly considered as buffing and therefore gives combat to shaman

Flametongue totem behaves the same.

https://youtu.be/a76Bp88SExs

**Expected behaviour:**

**Proof for expected behavior:**

**Comment by Aggrend** [comment]
This is correct behavior. Not a bug.
