### ISSUE TITLE
Forever combat bug with pet

### ISSUE THREAD

**Issue by Klimpb** [Aeded/BCC_Buglist#24]
1. Have your pet get in pvp combat
2. Buff pet
3. Have pet stop engaging in combat
4. Keep buffing pet
5. Both the player and pet are now forever in combat as long as you keep buffing every 5 sec or so."

https://streamable.com/1o0v9e

**Comment by Klimpb** [comment]
Still present
https://streamable.com/soyek2

**Comment by Aggrend** [comment]
This is consistent with how this works in the reference client. NAB for now.
