### ISSUE TITLE
Reflective shield - No spell pushback

### ISSUE THREAD

**Issue by Klimpb** [Aeded/BCC_Buglist#25]
Dot damage on a priest with Reflective shield talent doesn't cause spell pushback, it should.

**Comment by Klimpb** [comment]
Some proof from some time back
http://www.arenajunkies.com/topic/26184-priest-reflective-shield/?p=217518 (Two posts in here mentioning it does work.. Link completely dead and there is no archive of it.... Though I may have it stored somewhere, will try find it)

EDIT: http://web.archive.org/web/20130313233210/http://www.arenajunkies.com/topic/2784-why-not-reflective-shield/
A comment mentions pushback on spells.

**Comment by Aggrend** [comment]
Not a bug. Tested in reference and this does not cause pushback there either.
