### ISSUE TITLE
Inspecting players and changing targets

### ISSUE THREAD

**Issue by Klimpb** [Aeded/BCC_Buglist#31]
**Current behaviour:**
If you're inspecting player A and want to inspect player B, you have to right click and inspect him again after having targeted him
https://streamable.com/8zolek

**Expected behaviour:**
When inspecting player A, if you target player B and are within inspect range, the inspect window should simply swap to player B without having the need to right click and inspect again

**Proof for expected behavior:**

**Comment by Aggrend** [comment]
I'm dubious that this is actually a bug. I'd like to see proof of this occuring in actual TBC.

**Comment by Aeded** [comment]
I have no clue if this would be purely Interface bug. But it is possible on old tbc interface to change targets while inspecting. Obviously this is very minuscule issue so I think best course of action is to wait untill we get TBC version of inspect (talents+pvp tab etc) maybe it will work then.

But just in case this was purely interface bug, then this is on old client inspect (all addons disabled) https://streamable.com/zz685t

Like I previously mentioned this is very minor and I can imagine there are more important matters needed to be delt with aswell. So I wont be searching for a video proof from retail tbc as im very unlikely to find one.

**Comment by Aggrend** [comment]
Yeah, I wouldn't spend much time on it, for sure.
