### ISSUE TITLE
Heartbeat resist on improved Freezing Trap

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#33]
**Current behaviour:**
While testing something else with hunter, we encountered improved Freezing Trap ending prematurely several times, which led us to believe that somehow Heartbeat resist is somehow still in the game. Did not see any other CC break on heartbeat other than Freezing trap (did not test it though)

**Expected behaviour:**
Heartbeat resist in PvP was removed in 2.0.1

**Proof for expected behavior:**
"In PvP, Crowd Control effects will last no longer than 12 seconds instead of the full duration, with a chance of a heartbeat resist."
https://wowwiki-archive.fandom.com/wiki/Patch_2.0.1

**Comment by Aeded** [comment]
Apparently not only Freezing Trap
https://clips.twitch.tv/FaintMoldySquidTriHard-QAWDhmsEmNXU_hkc

**Comment by Aggrend** [comment]
This is not a bug. Heartbeat resists existed through all of TBC.
