### ISSUE TITLE
Nameplate castbars

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#34]
**Current behaviour:**
1) Icon of the casted spell is overlayed by some kind of texture
2) Nameplate Castbar is still being shown if mob is interrupted outside of the nameplate range https://streamable.com/x1rcs9
3) Castbar is often erroneously placed on different mob with same name.

On original TBC client, nameplate castbars were terrible too and worked very similarly. Sadly there was no way to fix their proper functionality through community AddOns because of the lack of propper client-side support. Im hopeful this could change in BC Classic.

**Comment by Aggrend** [comment]
There's a fix now for the spell icon not showing up, but that's likely about as much as is going to be done here.
