### ISSUE TITLE
Fel Armor not Increasing Siphon Life Healing

### ISSUE THREAD

**Issue by Fierywind** [Aeded/BCC_Buglist#36]
**Current behaviour:** As seen in https://clips.twitch.tv/VibrantConsiderateWalrusTF2John-sHQBoQcehJ7uDd82 staysafe is healing for the same amount siphon life is ticking for (either 201 or 202 on 2 mobs, 180 on another).

**Expected behaviour:** Siphon Life healing should be increased by 20% or 26% when talented.

**Proof for expected behavior:** https://archive.org/details/Jebzig_-_Wanted_Midgets_-_2vs2_qualification_Warlock_2007-07-30_4.72

**Comment by Aeded** [comment]
https://github.com/Aeded/BCC_Buglist/issues/38 Will keep this report instead
