### ISSUE TITLE
DestroyTotem() function is protected

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#41]
**Current behaviour:**
DestroyTotem() is protected, 

**Expected behaviour:**
This function is crucial for shamans in PvP, it was not protected in TBC nor WotLK. Every single class can either cancel buffs or dismiss pets with a macro, without having to manualy click on interface. If this function stays protected then shamans will have way bigger disadvantage in high rated arena than they had in retail tbc.

From what I gathered it was made as protected some time during Classic aswell, which is huge mistake imo.

I understand that such function has no place in Shadowlands, because retail shaman is not build around totems at all. While in TBC&classic totems are huge part of the gameplay and so is destroying them in time when required.

I would be understanding if such change was affecting everyone, but this targets only shamans, class that is not great for pvp by default. Please consider making the function unprotected again, or give us another way to cancel our totems through macros/keybinds.

**Proof for expected behavior:**
https://wowpedia.fandom.com/wiki/API_DestroyTotem?oldid=1330076
https://wowpedia.fandom.com/wiki/API_DestroyTotem?oldid=3119099 (Listed as protected around MoP)

**Comment by Aeded** [comment]
I understand that lots of functions from old versions of the game had to be removed or made protected to reduce the possibilities of botting and automatization, but this is one of the examples that does way more harm than good. Id be disappointed if bots were  flying around in tbc like they do in classic, warlocks stomping my totems with petmacro and I wouldnt be able to cancel my totems through keybind.

Now that I think about it, warlocks and hunters have more comfortable&faster way of destroying my totems than I have myself.  😞

**Comment by Aeded** [comment]
Possible solutions:
**1. Allow DestroyTotem() in combat**
**2. Add option in keybindings to destroy each totem manualy.**
**3. Add macro command like /canceltotem1**

Ability to destroy your own totems individualy is key and has to be preserved, otherwise shamans would get into unfair position in contrast to retail tbc.

**Comment by Schaka** [comment]
Making it protected does nothing to prevent bots, as they inject into the client and will always have a way to call protected Lua functions. 

If they want to keep it protected, adding a macro command would make most sense, as that is how protected functions are usually circumvented - since you can't apply additional logic to it.

That and I really hope totem stomping macros will not be a thing

**Comment by Aggrend** [comment]
This is intended. Not A Bug.

**Comment by Aeded** [comment]
Thanks for making DestroyTotem() unprotected, fixed now 🥰

**Comment by Aggrend** [comment]
My last comment didn't age super well :)

It was intended, and then we decided that was silly for BC. Enjoy!
