### ISSUE TITLE
Arena draw distance issues - pet despawn

### ISSUE THREAD

**Issue by Klimpb** [Aeded/BCC_Buglist#47]
**Current behaviour:**
https://streamable.com/2d0azi

**Expected behaviour:**
Uncertain, however seeing as we have infinite range on nameplates and target arena1/2/3 implemented, then limiting the draw distance seems odd.

**Comment by Klimpb** [comment]
Seems to be fixed, needs to double check though,

**Comment by Aeded** [comment]
Retested, was able to see my pet across entire nagrand arena.
