### ISSUE TITLE
Frost Trap & Flare debuff "Leeway" is way too big

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#5]
**Current behaviour:**
When running through frost trap, slow applies when you are somewhere in middle of visual effect. Same behaviour happens when you are running out of frost trap, slow disappears when you are far from the edge of visual effect.

https://streamable.com/i9c0iq
https://streamable.com/te81vu
https://streamable.com/iuwb8s

**Expected behaviour:**
This "Leeway" should not be that huge considering we have 10ms batching. Application of the slow / flare should be more accurate to the visual effect on ground.

**Proof for expected behavior:**
Keep in mind in all these videos there was 400ms batching.

https://youtu.be/9qv4nbt-NNk?t=831
https://www.youtube.com/watch?v=GCaLwOW_tIY&t=241s
https://www.youtube.com/watch?v=cIG7hloWVcQ&t=559s
https://www.youtube.com/watch?v=cIG7hloWVcQ&t=562s
https://youtu.be/cIG7hloWVcQ?t=605

Flare and Frost trap
https://youtu.be/FAz6E6W4T-I?t=604

**Conclusion:**
I think that application and removal of the Frost Trap and Flare should be more consitent with the visual effect on ground, but there should be some trap "Leeway" to a degree as it is seen the listed retail videos, but current version feels quite wrong and inconsistent.

**Comment by Aggrend** [comment]
We took a pretty careful look at this with a few engineers reviewing it, and the behavior matched what we saw in reference pretty accurately. Not going to be digging too much more into this one and I'm calling it Not A Bug for now.

**Comment by Aeded** [comment]
Alright, thanks alot for looking into it! ❤️  I feel like flare has to be bugged though, because it lingers for very long time atleast when compared to retail videos. However since you said you took careful look I wont be digging into it either for now and focus on other bugs. In case some other compelling evidence comes up in the future, I will make new report.
