### ISSUE TITLE
Power Infusion and Icy Veins stack

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#52]
**Current behaviour:**
Power Infusion only:
![image](https://user-images.githubusercontent.com/45561230/114091437-f9f63a00-98b8-11eb-8383-0d56657413c0.png)
Power Infusion+ Icy Veins:
![image](https://user-images.githubusercontent.com/45561230/114091387-eb0f8780-98b8-11eb-83a1-1b231dfd1a9e.png)

**Expected behaviour:**
"Patch 2.4.0 (2008-03-25): Infuses the target with power, increasing their spell haste by 20% and reducing the mana cost of all spells by 20%. Lasts for 15 seconds. This will not stack with **other haste effects**, such as Heroism or Bloodlust."

I should be still able to have both buffs at the same time thought, getting 20% haste and 30% mana reduction

**Comment by Fierywind** [comment]
The full wording of the 2.4 patch note makes it more explicit: 
Power Infusion: Infuses the target with power, increasing their spell haste by 20% and reducing the mana cost of all spells by 20%. Lasts for 15 seconds. This will not stack with other haste effects, such as Heroism, Bloodlust, or **Icy Veins.**
