### ISSUE TITLE
It is possible to run across armed Hunter Trap without triggering it.

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#6]
**Current behaviour:**
Very inconsistently it is possible to run over Hunter´s Trap without triggering it. Ive tested this over an hour and I cannot pin out whats causing the issue. 😞 

It is possible to run over trap while stealthed or by using 70% sprint. To make things harder, when tested with 100% mount, trap triggered late, but all the time consistently.

https://streamable.com/hd6gmb
https://streamable.com/1byr2a
https://streamable.com/97xjwm

**Expected behaviour:**
Traps should trigger consistently.

**Proof for expected behavior:**

**Comment by watchyoursixx** [comment]
Adding a note here that classic had this issue as well and it was determined NAB. 
![image](https://user-images.githubusercontent.com/47162044/113396388-7775f380-9369-11eb-8283-df173c747911.png)

Now whether this changed or not in TBC I'm not sure, but I'd be surprised if it did change unfortunately..

**Comment by Aeded** [comment]
I can understand charge not triggering traps, but why am I able to run over them in stealth etc?

As I already mentioned in the discussion, this was perfectly fine when all other classes play on 400ms batching and everyone had one or two abilities crippled by this artificial delay. Now that batching has been reduced to 10ms and all classes are positively affected by it, I dont see the slightest reason why Hunter´s Trap should stay behind crippled by this #nochanges nonsense.

**Comment by Aggrend** [comment]
This is another thing that we took a very careful look at, and it mostly matches reference. NAB for now.

**Comment by Aeded** [comment]
Alright, I appriciate that you looked into it! In case Ill find some other evidence I will make new report. Closing for now
