### ISSUE TITLE
Lightning Overload double procs

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#66]
**Current behaviour:**
Currently it is possible to double proc Lightning Overload with Chain Lightning. Tested Lightning bolt but in 300 casts I didnt see a double LO proc single time.
The second LO proc from Chain Lightning does same demage as first overload (which is odd)
https://streamable.com/f66rbe

Ive been trying to research this in past to find out whether LO can proc off itself, and I found out that early version of LO (5% chance, full dmg) was able to proc off itself, while 20% version was not able to proc off a proc. But I researched it only by looking at all old elemental shaman videos I could find, trying to look for the second proc. So not much of a certainty there.

It would be most welcomed if we could get some confirmation / comparison to reference client on whether double proccing is intended in 2.4.3 state or not.

...Or perhaps reference client will be "consistently inconsitent" aswell and only chain lightning will be able to double proc.

**Comment by Aggrend** [comment]
This is, in fact, consistently consistent with reference. ;)

Not a bug.
