### ISSUE TITLE
Intercepting/Charging Focus Target, sets auto attack on Focus Target

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#81]
**Current behaviour:**
While having Auto Attack set on your target, Intercepting / Charging focus target changes your Auto Attack to focus target.
https://streamable.com/dz58tc

**Expected behaviour:**
Intercepting / Charging focus target shouldnt chage your Auto Attack target.

**Proof for expected behavior:**

**Comment by riesza** [comment]
https://github.com/magey/tbc-warrior/issues/63#issuecomment-833971163

**Comment by Aeded** [comment]
Aggrend´s reply on magey´s report specificaly mentions Intercept, however this same behaviour can be seen with Feral Charge and Charge.
