### ISSUE TITLE
Bloodlust and Icy Veins do not stack

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#83]
**Current behaviour:**
After https://github.com/Aeded/BCC_Buglist/issues/52 got fixed, Icy Veins and Bloodlust/Heroism stopped stacking. Patch note mentioned in the original report was reffering only to Power Infusion not stacking with other haste effect.

https://streamable.com/grro20

**Expected behaviour:**
Bloodlust and Icy Veins should still stack.

**Comment by Cleavis** [comment]
Here's a sunwell video where they are stacking:

https://youtu.be/fQqx9YGr8xo?t=4m53s
