### ISSUE TITLE
Frost Nova doesn't break despite high damage

### ISSUE THREAD

**Issue by riesza** [Aeded/BCC_Buglist#91]
Figured I'd open an issue because this will make arena a mess.

**Current behaviour:**
More often than not, Frost Nova will just dissipate on its own before breaking despite constant high damage. Especially Ice Lance doesn't seem to contribute much to it breaking. It seems more likely to break after Frostbolt > Cone of Cold than from 4 or 5 Ice Lance crits.
![tlxUv4v](https://user-images.githubusercontent.com/1399263/118265611-b5fae400-b4b9-11eb-8e65-ae62a6352a3d.png)
![TfsIYFi](https://user-images.githubusercontent.com/1399263/118265614-b85d3e00-b4b9-11eb-8918-ed8965374682.png)
![pDh960y](https://user-images.githubusercontent.com/1399263/118265620-ba270180-b4b9-11eb-86ec-612d068c2e00.png)
![5cjW6Ok](https://user-images.githubusercontent.com/1399263/118265626-bb582e80-b4b9-11eb-8259-84edb9a0c7de.png)
![SKlDzXf](https://user-images.githubusercontent.com/1399263/118269243-c9f51480-b4be-11eb-9cba-fabcb555179d.png)
https://clips.twitch.tv/AggressiveIncredulousKumquatPeteZaroll-uHGjB0ADxaOz89uq

**Expected behaviour:**
Bit vague but Nova is supposed to have a high likelihood of breaking after high damage (e.g. a Shatter combo).

**Proof for expected behavior:**
This is difficult to provide good proof for but it fairly consistently doesn't break on the TBC beta unlike most of what I remember and can find in various retail TBC videos.
https://youtu.be/IB7bUNWTlh4?t=1287
https://youtu.be/m14rSFA7b4A?t=1457
https://youtu.be/nE9444jWWDw?t=40

**Comment by Aeded** [comment]
This issue was reviewed by devs thoroughly several times. Outcome was that current behaviour is same as on reference client, and that once people get more spell demage this issue might sort itself out.
So this is not going to get changed in terms of "bug fixing" 😐  however devs seemed opened to the idea of making #somechanges in the future to make it more balanced.

**Comment by Aeded** [comment]
Well few hours later and its all different https://us.forums.blizzard.com/en/wow/t/frost-nova-bug-going-live/966289
