### ISSUE TITLE
Vindication proc has no chance for double judgement of wisdom proc

### ISSUE THREAD

**Issue by Speankitsover** [Aeded/BCC_Buglist#93]
**Current behaviour:**
Has no chance of giving judgement of wisdom proc

**Expected behaviour:**
Should give chance to proc extra judgement of wisdom proc

**Proof for expected behavior:**
https://imgur.com/zNcZlaf
https://www.youtube.com/watch?v=UyooXkH6mT8
Notice the "immune" the paladin gets from hitting the boss, this is vindication proccing, also have a look at judgement of wisdom procs, the +74 mana return.

**Comment by Aeded** [comment]
This has been already discussed by devs and outcome was that after testing in reference client they conformed it is working as intended (for now).

**Comment by Speankitsover** [comment]
The most important part about ret paladins regarding mana management pve-wise and pvp-wise  is not working. One of the lesser specs dont even get their most important feature working. Unlucky
