### ISSUE TITLE
Reckoning, does it proc on dot damage? send help

### ISSUE THREAD

**Issue by Speankitsover** [Aeded/BCC_Buglist#94]
**Current behaviour:**
Does not proc from dot ticks

**Expected behaviour:**
Should maybe proc on dot ticks? Need help research

**Proof for expected behavior:**
https://wowwiki-archive.fandom.com/wiki/Reckoning_(old)
- Reckoning is triggered by any damage, including spells, melee attacks, ranged attacks, and environmental effects, such as campfire damage.

**Comment by Aeded** [comment]
It is not supposed to proc from dots or debuff applications, only procs from direct demage.
Feel free to provide video evidence of reckoning procing from dots. (Or any other legitimate source other than wowwiki.)
